# Generated by Django 5.0.7 on 2024-08-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_personid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwords',
            field=models.JSONField(default=list),
        ),
    ]
